name: Makefile CI

on:
  workflow_dispatch:
  push:
    branches: [ "emt" ]
  pull_request:
    branches: [ "emt" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - name: checkout
      uses: actions/checkout@v4

    - name: 
      run: | 
        cd ${{ github.workspace }}/ 
        make all
